# -*- coding: utf-8 -*-
"""hello.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13ze2wdiqMXckKwYty577aAMHRO90NYo0
"""

from flask import Flask, request, abort
from linebot import LineBotApi, WebhookHandler
from linebot.exceptions import InvalidSignatureError
from linebot.models import  MessageEvent, TextMessage, TextSendMessage
import pya3rt
# from flask_ngrok import run_with_ngrok

app = Flask(__name__)
# run_with_ngrok(app)

# CHANNEL_ACCESS_TOKEN = os.environ["CHANNEL_ACCESS_TOKEN"]
# CHANNEL_SECRET = os.environ["CHANNEL_SECRET"]
# line_bot_api = LineBotApi(CHANNEL_ACCESS_TOKEN)
# handler = WebhookHandler(CHANNEL_SECRET)

line_bot_api = LineBotApi("DfDcNGFPREH1hghXwwXfWZ30iMa9dxjDyekIkUnWUsyAYBHbJAL6PPPUM8GvIuJClFyrmgAiHzvChcA93HrtUFha7uENwXHTSQKskL0LAzQmEAMyaElQnAmCGPXShDQUpUHzOnPnWSVaZyz8XtiZsAdB04t89/1O/w1cDnyilFU=")
handler = WebhookHandler("b986779e8adf0139bb37346cae2e00ec")

@app.route("/callback", methods=['POST'])
def callback():

    signature = request.headers["X-Line-Signature"]
    body = request.get_data(as_text=True)
    app.logger.info("Request body:" + body)

    try:
        handler.handle(body, signature)
    except InvalidSignatureError:
        abort(400)

    return 'OK'

@handler.add(MessageEvent, message=TextMessage)
def handle_message(event):
    message = talk_ai(event.message.text)
    line_bot_api.reply_message(event.reply_token, TextSendMessage(text=message))

def talk_ai(word):
    apikey = 'DZZejeeQuT5pnkCbLZtaLHUg2a5ftDhL'
    client = pya3rt.TalkClient(apikey)
    client_talk = client.talk(word)
    return client_talk['results'][0]['reply']

if __name__ == '__main__':
    app.run()